version: 0.0
os: linux
files:
 - source: helloworld.js
   destination: /home/ec2-user/
 
 - source: scripts/helloworld.service
   destination: /lib/systemd/system/

hooks:
  BeforeInstall:
    - location: script/stop.sh
      timeout: 30
      runas: root
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 30
  ValidateService:
    - location: scripts/validate.sh
      
